### ISSUE TITLE
Latest MacOS version keeps searching 

### ISSUE THREAD

**Issue by vanvught** [hippyau/rnc#2]
-> https://github.com/hippyau/rnc/releases/download/MacOS/rnc-0.2.zip

https://user-images.githubusercontent.com/4319913/134738788-09a1a8c1-8e23-43ea-a7d9-b4e3ec533f9d.mov

**Comment by vanvught** [comment]
```
arjanvanvught@MacBook-Air MacOS % ./rnc 
flutter: mDNS: Search...
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Operation not permitted, errno = 1), address = 0.0.0.0, port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:981)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:106)
<asynchronous suspension>
#2      NodeRecords.findDevices (package:rcmnode/nodes.dart:84)
<asynchronous suspension>
```

**Comment by vanvught** [comment]
I've found :[https://flutter.dev/desktop#setting-up-entitlements]( https://flutter.dev/desktop#setting-up-entitlements)

**Comment by hippyau** [comment]
Thanks Arjan,  yes and sorry its a permission issue, i applied to the debug
but not the release 🤦 I've just been at work all day and won't get a
chance to fix tonight sorry....   sorry!  Will fix asap.

**Comment by hippyau** [comment]
Hi Arjan,  I accidentally omitted the 'be a network server' entiltement for the release build that I had added to the previous debug build,  please try this one...

https://github.com/hippyau/rnc/releases/tag/MacOS

**Comment by vanvught** [comment]
Hi Hip, the new build is working great. Thank you! Groet, Arjan

**Comment by hippyau** [comment]
There is a new release with the Art-Net Time Code reader, and UDP realtime commands.  I now realize I am using the release system on github wrong, it's at the same MacOS tag as above for now :)
