### ISSUE TITLE
Enhancement: Add 'disable' for Port direction

### ISSUE THREAD

**Issue by vanvught** [hippyau/rnc#9]
Hi Hip,

Currently we can only select '`input`' or '`output`'. It is not possible to disable a port.

![Schermafbeelding 2022-06-05 om 11 46 17](https://user-images.githubusercontent.com/4319913/172044747-5093829f-aa90-4072-a55f-5b75389f2c08.png)

**Comment by hippyau** [comment]
Fixed in https://github.com/hippyau/rnc/commit/823e860bcb45d7393df23edd8a700f5854b59548
![image](https://user-images.githubusercontent.com/36442309/197121044-c364e737-ddf1-4756-a685-2aa7f705a058.png)
